apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  ports:
  - port: 8080          # service port (inside cluster)
    targetPort: 8080    # container port
    nodePort: 31933     # external Minikube port
  selector:
    app: spring-boot-app